# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12-browsers
        environment:
          - LANG: ja_JP.UTF-8
          - LANGUAGE: ja_JP.UTF-8

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          command: make ci
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - google-search-datepicker.crx
            - version

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
  daily_workflow:
    triggers:
      - schedule:
          cron: "0 9 * * *" # 18:00 JST
          filters:
            branches:
              only:
                - master
    jobs:
      - build
