# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12-browsers
        environment:
          - LANG: ja_JP.UTF-8
          - LANGUAGE: ja_JP.UTF-8

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test

      # archive
      - run:
          name: "Archive google-search-datepicker.crx"
          command: |
            mkdir -p /tmp/workspace
            ./node_modules/.bin/crx pack -o /tmp/workspace/google-search-datepicker.crx apps 
            jq .version_name apps/manifest.json | tr -d '"' > /tmp/workspace/version

      # run tests!
      - run: yarn integration-test

      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - google-search-datepicker.crx
            - version

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
  daily_workflow:
    triggers:
      - schedule:
          cron: "0 9 * * *" # 18:00 JST
          filters:
            branches:
              only:
                - master
    jobs:
      - build
