name: "Continuous Integration"

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write
  actions: read

env:
  node-version: "22.11.0"

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: enable corepack
        run: corepack enable

      - name: Setup Node
        uses: ubicloud/setup-node@v4
        with:
          node-version: ${{ env.node-version }}
          cache: "pnpm"

      - name: Run CI
        run: make ci
